# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40e0abc5b6c73d50b3724f7c7a78b0adefd1e2e9581ff9240919c22727124dd8738951ef1151fc1b442b34f4ae785c54f6674ad0e481fe5f21d607e37b304ea1

test:
  secret_key_base: 7d2c69fbd99acf4834c1ed8ead50e434dfb5be304e907342efe03a671924649beb3cabba412c4ce2ba47b599aeffb0de59dcbfb128ac3486867ada94170562cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
